### ISSUE TITLE
Cannot pull Docker image from repo, not public?

### ISSUE THREAD

**Issue by l33tlamer** [dyrector-io/darklens#2]
Hey there!

I wanted to try out your newly released darklens, but when trying to pull the image `ghcr.io/dyrector-io/darklens:latest` i keep getting:

`Error response from daemon: Head "https://ghcr.io/v2/dyrector-io/darklens/manifests/latest": unauthorized`

And there is package listed under this repo: https://github.com/orgs/dyrector-io/packages?repo_name=darklens

Could it be that someone forgot to set the package to public?

**Comment by potter-jason** [comment]
Same issue here

**Comment by l33tlamer** [comment]
> Same issue here

Fyi someone mentioned on Reddit that they are now aware of the mistake and that it would be fixed sometime next week.

**Comment by l33tlamer** [comment]
It appears to be fixed now, i can pull `ghcr.io/dyrector-io/darklens:latest`
